class SoftPhoneEvents {
   static EVENT_INITIAL_SOFT_PHONE = "EVENT_INITIAL_SOFT_PHONE";
   static EVENT_INITIAL_STRINGEE_SOFT_PHONE = "EVENT_INITIAL_STRINGEE_SOFT_PHONE";
   static EVENT_MAKE_CALL_FROM_STRINGEE = "EVENT_MAKE_CALL_FROM_STRINGEE";
   static EVENT_UNREGISTER_STRINGEE_PUSH = "EVENT_UNREGISTER_STRINGEE_PUSH";
   static EVENT_HAS_OTHER_INCOMING_CALL = "EVENT_HAS_OTHER_INCOMING_CALL";
}

export default SoftPhoneEvents;